require 'bundler'

Bundler::GemHelper.install_tasks

begin
  require 'spree/testing_support/extension_rake'
  require 'rubocop/rake_task'
  require 'rspec/core/rake_task'

  RSpec::Core::RakeTask.new(:spec)

  RuboCop::RakeTask.new

  task default: %i(first_run set_devise_secret_key rubocop spec)
rescue LoadError
  # no rspec available
end

task :first_run do
  if Dir['spec/dummy'].empty?
    Rake::Task[:test_app].invoke
    Dir.chdir('../../')
  end
end

desc 'Generates a dummy app for testing'
task :test_app do
  ENV['LIB_NAME'] = '<%=file_name%>'
  Rake::Task['extension:test_app'].invoke
end

desc 'Generates a devise secret key for the dummy app'
task :set_devise_secret_key do
  path = 'spec/dummy/config/initializers'
  file_path = path + '/devise.rb'

  unless File.exist?(file_path)
    FileUtils.mkdir_p(path)
    File.open(file_path, 'w') do |file|
      file.write("Devise.secret_key = '454360bb1e74cc798944b7defda59b291a40b376e71b48c2b1615134859400af0ebdbd841460e8f5992d152fb55444d29f79'\n\n")
    end
  end
end
